# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffff', '0002_auto_20171001_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=128)),
                ('issent', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='customer',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='service_provider',
            field=models.CharField(max_length=64),
        ),
    ]
