# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffff', '0003_auto_20171003_0216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='fromid',
            field=models.CharField(default='hey', max_length=32),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='toid',
            field=models.CharField(default='hey', max_length=32),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(default='hey', max_length=128),
        ),
    ]
